name: ci pipeline
on:

#   push:
#     branches: 
#       - "*"

  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

env:
  BASE_URL: 'https://magento.softwaretestingboard.com/'
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  critical-test-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run critical tests
        uses: ./.github/actions/e2e-tests
        with:
          test_tags: '@LOGIN|@SIGN_UP'

  regression-test-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: run regression tests
        uses: ./.github/actions/e2e-tests
        with:
          test_tags: '@LOGIN|@SIGN_UP|@MEN_CATEGORY_SHOPPING'

  sanity-test-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run sanity tests
        uses: ./.github/actions/e2e-tests
        with:
          test_tags: '@MEN_CATEGORY_SHOPPING|@SANITY'



  # status_checks:
  #   name: E2E status checks
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event_name == 'pull_request' }}
  #   needs: test 
  #   steps:
  #     - name: determine status check conclusion
  #       id: status-check-status
  #       run: |
  #         if [[ "${{ needs.test.result == 'failure' }}" ]]; then
  #           echo "status=failure" >> $GITHUB_OUTPUT
  #         else
  #           echo "status=success" >> $GITHUB_OUTPUT
  #         fi
  #     - name: set pr status checks
  #       uses: teamniteo/pull_request_status_action@v1.0.0
  #       with:
  #         pr_number: ${{ github }}
  #         state: ${{ steps.status-check-status.outputs.status }}
  #         repository: Romarionijim/Playwright-TypeScript-Mini-Project
  #       env:
  #         GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
