name: ci pipeline
on:
  workflow_dispatch:
#   push:
#     branches: 
#       - "*"
  pull_request:
    branches: [ main, master ]
env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base_urls: ['https://magento.softwaretestingboard.com/']
        browsers: ['chromium']
        greps: ['@LOGIN', '@SIGN_UP', '@SANITY', '@MEN_CATEGORY_SHOP']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: BASE_URL=${{ matrix.base_urls }} npx playwright test --grep ${{ matrix.greps }} --project=${{ matrix.browsers }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{matrix.greps}}-${{ matrix.browsers }}
        path: playwright-report/
        retention-days: 30
    - name: Deploy Playwright report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report/