name: ci pipeline
on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: [ main, master ]
env:
  AWS_ACCESS_KEY: ${{  secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{  secrets.AWS_SECRET.KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base_urls: ['https://magento.softwaretestingboard.com/']
        browsers: ['chromium', 'firefox']
        greps: ['@login']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: BASE_URL=${{ matrix.base_urls }} npx playwright install --with-deps --grep ${{ matrix.greps }} --project=${{ matrix.browsers }}
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{matrix.greps}}-${{ matrix.browsers }}
        path: playwright-report/
        retention-days: 30
        
  deploy:
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2  
